const productData = [
  {
    id: 1,
    name: "Burger",
    description: "Delicious hamburger with all the fixings.",
    price: 5.99,
    image: "hello",
    quantity: 1,
    category: "Kids",
  },
  {
    id: 2,
    name: "Sandwich",
    description: "Satisfy your cravings with a crispy chicken sandwich.",
    price: 6.99,
    image: "hello",
    quantity: 1,
    category: "Adults",
  },
  {
    id: 3,
    name: "Burger",
    description: "Get your cheese fix with our classic cheeseburger.",
    price: 4.99,
    image: "hello",
    quantity: 1,
    category: "Adults",
  },
  {
    id: 4,
    name: "Burger",
    description: "Enjoy the perfect combination of savory and sweet with our BBQ bacon burger.",
    price: 7.99,
    image: "hello",
    quantity: 1,
    category: "Kids",
  },
  {
    id: 5,
    name: "Nuggets",
    description: "Crispy and delicious, our chicken nuggets are perfect for snacking.",
    price: 3.99,
    image: "hello",
    quantity: 1,
    category: "Adults",
  },
  {
    id: 6,
    name: "Hotdog",
    description: "Our classic hot dog is the perfect meal on the go.",
    price: 2.99,
    image: "hello",
    quantity: 1,
    category: "Kids",
  },
  {
    id: 7,
    name: "Sandwich",
    description: "Get a taste of the sea with our crispy fish sandwich.",
    price: 5.99,
    image: "hello",
    quantity: 1,
    category: "Kids",
  },
  {
    id: 8,
    name: "Lavash",
    description: "Get a taste of the sea with our crispy fish sandwich.",
    price: 5.99,
    image: "hello",
    quantity: 1,
    category: "Kids",
  },
  {
    id: 9,
    name: "Non burger",
    description: "Get a taste of the sea with our crispy fish sandwich.",
    price: 5.99,
    image: "hello",
    quantity: 1,
    category: "Adults",
  },
];